apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

secretGenerator:
- name: cloudflare-sync
  literals:
  - CF_API_KEY=${CF_API_KEY}

images:
- name: registry.digitalocean.com/destashd/kubernetes-cloudflare-sync
  newName: registry.digitalocean.com/destashd/kubernetes-cloudflare-sync
  newTag: "{{.Env.CIRCLE_SHA1}}"
